GENERIC_TERMS = [
    "model",
    "method",
    "approach",
    "system",
    "process",
    "technique",
    "algorithm",
    "framework",
    "tool",
    "solution",
    "application",
    "architecture",
    "placeholder"
    "network",
    "structure",
    "component",
    "element",
    "feature",
    "parameter",
    "setting",
    "configuration",
    "task",
    "function",
    "operation",
    "step",
    "part",
    "phase",
    "module",
    "layer",
    "unit",
    "example",
    "case",
    "type",
    "version",
    "level",
    "result",
    "output",
    "input",
    "data",
    "information",
    "analysis",
    "study",
    "experiment",
    "test",
    "evaluation",
    "performance",
    "accuracy",
    "score",
    "metric",
    "baseline",
    "comparison",
    "modeling",
    "training",
    "learning",
    "prediction",
    "classification",
    "generation",
    "recognition",
    "detection",
    "extraction",
    "representation",
    "embedding",
    "mapping",
    "vector",
    "signal",
    "pattern",
    "sample",
    "instance",
    "concept",
    "object",
    "entity",
    "field",
    "domain",
    "category",
    "class",
    "group",
    "set",
    "collection",
    "batch",
    "item",
    "token",
    "word",
    "sentence",
    "document",
    "corpus",
    "language",
    "text",
    "image",
    "audio",
    "video",
    "variable",
    "property",
    "attribute",
    "option",
    "choice",
    "selection",
    "strategy",
    "protocol",
    "policy",
    "rule",
    "criterion",
    "limit",
    "constraint",
    "boundary",
    "condition",
    "effect",
    "impact",
    "influence",
    "change",
    "difference",
    "variation",
    "trend",
    "distribution",
    "range",
    "scale",
    "degree",
    "quality",
    "kind",
    "form",
    "style",
    "mode",
    "dataset",
    "parameters",
    "hyperparameters",
    "configuration",
    "settings",
    "options",
]

EXCLUDE = ["**Patreon special mentions**",
"Please see the Responsible Use Guide available", 
"More Information Needed"]

WEAK_HEADS = {
    # General catch-alls
    "thing", "things", "stuff", "one", "ones", "something", "anything", 
    "everything", "nothing", "matter", "item", "object", "element", "piece", "bit",

    # Abstract / vague nouns
    "aspect", "part", "section", "portion", "factor", "component", "piece", 
    "case", "point", "side", "area", "kind", "type", "sort", "form", "way", 
    "issue", "question", "problem", "situation", "circumstance", "context", 
    "condition", "state", "stage", "step", "process", "basis", "approach",

    # Placeholder / pronoun-like
    "someone", "somebody", "anyone", "anybody", "everyone", "everybody", 
    "noone", "nobody", "whomever", "whoever", "whatever", "whichever",

    # Overly generic containers
    "example", "sample", "instance", "case"  # <- careful: "model" is domain-specific, so maybe keep?
}